### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp' -> 'spotify_data.csv'

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/spotipy_currently_playing_file#10]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 122, in write_data_timer
    write_data_source(get_track(), get_user(), counter % 10 == 0)
  File "app.py", line 93, in write_data_source
    os.rename("tmp", filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tmp' -> 'spotify_data.csv'
```

**Comment by Rosuav** [comment]
Might be best to switch it around and directly write to the output file? Not sure. What was the reason for writing to a temp file and then moving it over?

**Comment by MikeiLL** [comment]
Because of https://stackoverflow.com/questions/62707420/continuously-update-a-file

"It even sort of works. I can open or cat info.txt and intermittently see:

nothing
a numeral from an increasing series
Why nothing sometimes?"

**Comment by Rosuav** [comment]
Fair enough. That's not the same sort of problem as here though, since you're not actually *continuously* updating the file - you sleep, you do network transactions, and THEN you update the file.

**Comment by MikeiLL** [comment]
But I believe vMix is going to be continually pinging the file, by the millisecond.

**Comment by Rosuav** [comment]
Fair enough. It's still unlikely to be a problem, though.

I don't understand how you could get past the 'with' block without either having created the file, or raised an exception. Might need a bit more logging to figure that out.

**Comment by MikeiLL** [comment]
It does seem to be working. One option would be wrapping the os.rename line in a try, except FileNotFoundError block.

I will also try just writing the file directly, as you suggest.

**Comment by MikeiLL** [comment]
Seems to be working.
