### ISSUE TITLE
Track multiple users and retain their authorization.

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/spotipy_currently_playing_file#6]
I think that we want a unique, local `cache_path` for each user (instructor). Currently it's a file:

```
$ cat .cache-test 
{"access_token": "BQDrLfxxx-xxWw", "token_type": "Bearer", "expires_in": 3600, "refresh_token": "AQA6lXetcetcetc", "scope": "user-read-currently-playing", "expires_at": 1594514350}
```

Ideally the user name would be the username from Spotify. This might be a bit of a chicken and egg scenario. But we need to specify a `cache_path` for `spotipy.oauth2.SpotifyOAuth` before the Spotify username is returned.

One option is to have local usernames that don't match with Spotify, which might be fine. Another option would be to have a generic `cache_path` which is used for getting user names, and then re-instantiate `spotipy.oauth2.SpotifyOAuth` with Spotify username.

**Comment by MikeiLL** [comment]
I think that we want a unique, local `cache_path` for each user (instructor). Currently it's a file:

```
$ cat .cache-test 
{"access_token": "BQDrLfxxx-xxWw", "token_type": "Bearer", "expires_in": 3600, "refresh_token": "AQA6lXetcetcetc", "scope": "user-read-currently-playing", "expires_at": 1594514350}
```

Ideally the user name would be the username from Spotify. This might be a bit of a chicken and egg scenario. But we need to specify a `cache_path` for `spotipy.oauth2.SpotifyOAuth` before the Spotify username is returned.

One option is to have local usernames that don't match with Spotify, which might be fine. Another option would be to have a generic `cache_path` which is used for getting user names, and then re-instantiate `spotipy.oauth2.SpotifyOAuth` with Spotify username.

**Comment by Rosuav** [comment]
Seems like you'll need to have some sort of per-session authentication. The easiest way to do this would be to have the instructor log in using Spotify each session, and then be identified by some sort of user ID, which could then be stored in Flask's session object. Fairly straight-forward as long as you don't need to retain too much info, or if you're okay with the Spotify account being the sole fundamental.

The big question is, what chooses where the fundamental output goes? #4 wants a file, and if there are multiple authenticated users, there would have to be multiple output files.

**Comment by MikeiLL** [comment]
As of right now, we only need a single source of output data. It's just a single row of csv data.
