### ISSUE TITLE
Data isn't being written for new user

### ISSUE THREAD

**Issue by MikeiLL** [MikeiLL/spotipy_currently_playing_file#7]
When a new user authenticates, the data stops being written.

I think this might be because upon logout, the two threads need to be stopped or joined or stopped and joined.

I have also tried using multiprocessing, but so far without success.

The reason I thought it would make sense to use threading is so that one thread can be `getting` the data from Spotify and the other `writing` the data.

I think that perhaps a queue should be holding the data from Spotify and yielding it as it's requested for writing.

Current approach is:

Upon app run:
```
update_data_process = multiprocessing.Process(target=spotify_data.update_data)
write_data_process = multiprocessing.Process(target=write_data_timer)
```

Upon user login:
```
try:
		update_data_process.start()
		print("Starting update_data_process")
	except AssertionError:
		print("update_data_process already started.")
	
	try:
		write_data_process.start()
		print("Starting write_data_process")
	except AssertionError:
		print("write_data_process already started.")
```

Upon logout:
```
try:
		update_data_process.terminate()
		print("Terminating update_data_process")
		write_data_process.terminate()
		print("Terminating write_data_process")
	except AttributeError: 
		print('Process not started')
```

However it doesn't seem like the processes are terminating, because when login occurs again, output is: `write_data_process already started.`

**Comment by Rosuav** [comment]
You shouldn't ever be catching AssertionError (outside of unit testing and such). I'm sure there must be a simpler way to do this than having multiple start and stop operations.

**Comment by MikeiLL** [comment]
Fixed with @Rosuav simplification of codebase.
